### ISSUE TITLE
Does this code works?

### ISSUE THREAD

**Issue by ColinBrosseau** [hellange/AD5761#1]
Not really an issue. I'm wondering if this code actually works. Couldn't make it work with Arduino UNO

Arduino Pin - AD5761 Pin
10 - 13
11 - 12
12 - 10
13 - 14

Vout is at a constant ~0.46 V.

I read the serial output and don't seems good:

```
Readback from control register before setting:
CMD:FF DATA:FF FF
Readback from control register after setting:
CMD:FF DATA:FF FF
```

**Comment by hellange** [comment]
Pretty sure this is the latest code that was tested successfully. I don't have the hardware easily available , but I can try to update this post when/if I get the hardware up'n running again.

**Comment by ColinBrosseau** [comment]
OK. It comes from a stupid non standard SSOP16 - DIP adapter. https://www.sparkfun.com/products/498
With pin correction, it works like a charm.

**Comment by hellange** [comment]
Looks like they have changed that in the update revision of their boards.
